### ISSUE TITLE
text-only expiration email

### ISSUE THREAD

**Issue by frisi** [collective/collective.pwexpiry#13]
for one of our customers the expiration warnings ended up in the spam folder.

i think this is because we're sending a html only email which many spam-checkers dislike

we either provide a text-only email or compute a multi-part email with text and html variants.

for the sake of simplicity i'd vote for text-only mails in this case.
otherwhise we'd need to maintain a text and html version (including translations) or compute the text version out of html using html2text or beautifulsoup or the like

@frapell are you ok with switching to a text only version?

**Comment by frapell** [comment]
@frisi Doesn't this send emails the same way Plone would send any other email? if so, would they also go to spam?

In response to your specific question, the notification is very simple and doesn't really need to be sent in HTML, so I'm fine moving it to text-only

**Comment by jochumdev** [comment]
This has been implemented in #15
