### ISSUE TITLE
No longer compatible with Plone 4.3

### ISSUE THREAD

**Issue by frisi** [collective/collective.pwexpiry#21]
filing a ticket to make sure the comment in https://github.com/collective/collective.pwexpiry/pull/19#issuecomment-349643672 does not get overlooked.

if it would just be a conditional import to fix the situation i'd have created a PR @frapell 
as i don't want to break plone5 support by re-adding plone4 support i think it's best that you take a look on this as you merged and mostly wrote the changes.

**Comment by frapell** [comment]
@frisi Yes, thank you for this!

I think we need to bring back everything that was removed in https://github.com/collective/collective.pwexpiry/pull/19/commits/bf1d4807b178ee97daaf4505911a3ae3768b21e0 with conditional imports and conditional zcml declarations, based on wether it is being used in P4 or P5...

**Comment by hvelarde** [comment]
@frapell I need to use this package for a customer on a Plone 4.3 site; I can try to bring compatibility back but I would need guidance.

**Comment by hvelarde** [comment]
it's worse than I expected: the package is completely broken, it doesn't work neither in Plone 5:

https://travis-ci.org/collective/collective.pwexpiry/jobs/449355376

**Comment by frapell** [comment]
@hvelarde I think doing what I mentioned in my last comment should be enough... 

The product is not completely broken, it looks like tests are

**Comment by hvelarde** [comment]
well, I reintroduce the code that was removed and I was not able to make it work; I even tested version 0.9.1 (just before your changes) and I was neither able to make it work.

probably I'm missing something, so the documentation may need some love also.

I would appreciate any hints.

**Comment by frisi** [comment]
fwiw: we use collective.pwexpiry-0.9.1 on a plone 4.3.15 site in production.
in order to help you @hvelarde it's necessary to state what exactly is not working for you: what do you do, what do you expect, what happens instead?

**Comment by hvelarde** [comment]
@frisi seems something was persisting on the ZODB and I had to remove the whole `var` directory; after that, I can see the package working.
