### ISSUE TITLE
Disable master protection

### ISSUE THREAD

**Issue by frapell** [collective/collective.pwexpiry#38]
@hvelarde please disable the protection where we cannot push directly to master. This is affecting the release process. This happened in #36, and it is happening again... I have released version 0.14.0 https://pypi.org/project/collective.pwexpiry/ and now I cannot push the commits zest.releaser did, to the repo...

After you disable it, please do not enable it again until it doesn't affect normal development process.

Thank you

**Comment by frapell** [comment]
@mauritsvanrees Is this something you can do? I do not have access to the "Settings" for this repo...

**Comment by gforcada** [comment]
Done
